routes/web.php
<?php

use App\Covenants;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::domain('ventajasmedicina.umax.edu.py')->group(function () {
      Route::get('/', function () {
          return view('landing.index');
      })->name('ventajas.medicina.index');

      Route::get('/index/portugues', function () {
          return view('landing.index_portugues');
      })->name('ventajas.medicina.portugues');
});

Route::group(['prefix'=>'admin','as'=>'admin.'], function(){
    Route::get('/', function () {
        return view('administration.index');
    })->name('dashboard')->middleware('auth');

    Route::resource('news', 'Admin\NewsController')->middleware('auth');
    Route::resource('banners', 'Admin\BannersController')->middleware('auth');
    Route::resource('covenants', 'Admin\CovenantsController')->middleware('auth');
});

Route::get('/', 'HomeController@index')->name('index');

Route::get('/noticias', 'HomeController@news')->name('noticias');

Route::get('/noticias/{id}/detail', 'HomeController@new')->name('noticias.detail');

Route::get('/divulgacion-cientifica', function (){
    $ids = [6,11,26,16,18,20,21,22,23,24,25,27,30,32,34,36,37,39,40,38,41,44,43,45];
    $news = \App\News::whereHas('categories', function ($q) {
        $q->where('id', 2);
    })->orderBy('datetime', 'desc')
        ->get();

    $news = $news->sortBy(function($model) use ($ids) {
        return array_search($model->getKey(), $ids);
    });

    return view('news.divulgacion', compact('news'));

})->name('divulgacion');


Route::get('/nosotros', function () {
    return view('about.index');
})->name('about');

Route::get('/medicina', function () {
    return view('about.medicina');
})->name('medicina');

Route::get('/enfermeria', function () {
    return view('about.enfermeria');
})->name('enfermeria');

Route::get('/virtual', function () {
    return view('about.virtual');
})->name('virtual');

/*
 * Convenios
 */
Route::get('/convenios', function () {
    $covenants = Covenants::orderBy('created_at', 'desc')->get();
    return view('about.convenios', compact('covenants'));
})->name('convenios');

Route::get('/convenios/{id}', function ($id) {
    $covenant = Covenants::find($id);
    return view('about.convenio_interna', compact('covenant'));
})->name('convenio.interna');

Route::get('/convenios_bk', function () {
    return view('about.convenios_bk');
});

Route::get('/convenios_bk/1', function () {
    return view('about.detail-convenio');
})->name('convenio-1');

Route::get('/convenios_bk/2', function () {
    return view('about.detail-convenio2');
})->name('convenio-2');

Route::get('/convenios_bk/3', function () {
    return view('about.detail-convenio3');
})->name('convenio-3');

Route::get('/convenios_bk/4', function () {
    return view('about.detail-convenio4');
})->name('convenio-4');

Route::get('/convenios_bk/5', function () {
    return view('about.detail-convenio5');
})->name('convenio-5');

Route::get('/convenios_bk/6', function () {
    return view('about.detail-convenio6');
})->name('convenio-6');



/*
 * Carreras
 */
Route::get('/postgrado', function () {
    return view('carreras.postgrado');
})->name('postgrado');

Route::get('/pregrado/tecnico-superior-farmacia', function () {
    return view('carreras.pregrado.tecnico_superior_farmacia');
})->name('pregrado-1');

Route::get('/pregrado/tecnico-superior-radiologia', function () {
    return view('carreras.pregrado.tecnico_superior_radiologia');
})->name('pregrado-2');

Route::get('/pregrado/tecnico-superior-laboratorio-clinico', function () {
    return view('carreras.pregrado.tecnico_superior_laboratorio');
})->name('pregrado-3');

Route::get('/pregrado/tecnico-superior-masaje-terapeutico', function () {
    return view('carreras.pregrado.tecnico_superior_masaje');
})->name('pregrado-4');

Route::get('/pregrado/tecnico-superior-enfermeria', function () {
    return view('carreras.pregrado.tecnico_superior_enfermeria');
})->name('pregrado-5');



Route::get('/contacto', function () {
    return view('about.contacto');
})->name('contacto');


Route::get('/maestria', function () {
    return view('postgrado.maestria');
})->name('maestria');

Route::get('/especializacion', function () {
    return view('postgrado.especializacion');
})->name('especializacion');

Route::get('/diplomado', function () {
    return view('postgrado.diplomado');
})->name('diplomado');

Route::get('/extension', function () {
    return view('extension.index');
})->name('extension');

Route::get('/investigacion', function () {
    return view('extension.investigacion');
})->name('investigacion');

Route::get('/politicas-investigacion', function () {
    return view('extension.politicas-investigacion');
})->name('politicas-investigacion');

Route::get('/lineas-investigacion', function () {
    return view('extension.lineas-investigacion');
})->name('lineas-investigacion');

Route::get('/actividades-investigacion', function () {
    return view('extension.actividades-investigacion');
})->name('actividades-investigacion');

Route::get('/investigadores-asociados', function () {
    return view('extension.investigadores-asociados');
})->name('investigadores-asociados');

Route::get('/revista-cientifica', function () {
    return view('extension.revista-cientifica');
})->name('revista-cientifica');

Route::get('/declaracion-privacidad', function () {
    return view('extension.declaracion-privacidad');
})->name('declaracion-privacidad');

Route::get('/equipo-editorial', function () {
    return view('extension.equipo-editorial');
})->name('equipo-editorial');

Route::get('/archivos', function () {
    return view('extension.archivos');
})->name('archivos');

Route::get('/envios', function () {
    return view('extension.envios');
})->name('envios');

Route::get('/revista-cientifica', function () {
    return view('extension.revista-cientifica');
})->name('revista-cientifica');

Route::get('/pastoral', function () {
    return view('extension.pastoral');
})->name('pastoral');

Route::get('/bienestar-estudiantil', function () {
    return view('bienestar.bienestar');
})->name('bienestar');

Route::get('/egresados', function () {
    return view('about.egresados');
})->name('egresados');

Route::get('/noticias/2', function () {
    return view('news.news-detail-2');
})->name('news-detail-2');

Route::get('/noticias/3', function () {
    return view('news.news-detail-3');
})->name('news-detail-3');

Route::get('/noticias/4', function () {
    return view('news.news-detail-4');
})->name('news-detail-4');

Route::get('/noticias/5', function () {
    return view('news.news-detail-5');
})->name('news-detail-5');

Route::get('/biblioteca-virtual', function () {
    return view('about.biblioteca');
})->name('biblioteca');

/*
 * Investigación -> Núcleos de Investigación
 */
Route::get('/innovacion-medica', function () {
    return view('nucleos.innovacion-medica');
})->name('innovacion-medica');

Route::get('/enfermedades-infecciosas', function () {
    return view('nucleos.enfermedades-infecciosas');
})->name('enfermedades-infecciosas');

Route::get('/nutricion-geriatria', function () {
    return view('nucleos.nutricion-geriatria');
})->name('nutricion-geriatria');

Route::get('/bioestadistica-aplicada-salud', function () {
    return view('nucleos.bioestadistica-aplicada-salud');
})->name('bioestadistica-aplicada-salud');

Route::get('/donacion-transplante-organos', function () {
    return view('nucleos.donacion-transplante-organos');
})->name('donacion-transplante-organos');

Route::get('/psiquiatria-salud-mental', function () {
    return view('nucleos.salud-mental');
})->name('salud-mental');

Route::get('/tecnologia-informacion-comunicacion-salud', function () {
    return view('nucleos.tecnologia-informacion-comunicacion-salud');
})->name('tecnologia-informacion-comunicacion-salud');


/*
 * MAILING
 */
Route::get('/mail/send/future', 'EmailsController@future')->name('mail.send.future');
Route::get('/mail/send/contact', 'EmailsController@contact')->name('mail.send.contact');

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
//http://ventajasmedicina.umax.edu.py/

/*Route::domain('{account}.example.com')->group(function () {
    Route::get('user/{id}', function ($account, $id) {
        //
    });
});*/

Route::get('ventajas/es', function (){
    return view('landing.index');
});
Route::get('ventajas/pt', function (){
    return view('landing.index_portugues');
});

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'content',
        'image_path',
        'image_name',
        'datetime',
        'published',
        'autor',
    ];

    public function categories()
    {
        return $this->belongsToMany(Category::class, NewCategory::class,
            'new_id', 'category_id');
    }
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Mail\contactMail;
use App\Mail\futureMail;
use App\News;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class NewsController extends Controller
{
    public function index(Request $request)
    {
        $news = News::orderBy('datetime', 'DESC')->paginate(20);

        return view('administration.news.index', compact('news'));
    }

    public function create()
    {
        $categories = Category::pluck('name', 'id');
        return view('administration.news.form', compact('categories'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|max:255',
            'content_text' => 'required',
            'categories' => 'required',
            'datetime' => 'required'
        ],[],[
            'content_text' => 'contenido',
        ]);
        //return redirect()->back()->withInput()->with('notification', json_encode(['type' => 'error', 'message' => 'Correcto']));
        try {
            \DB::beginTransaction();

            $new = new News();
            $new->title         = $request->title;
            $new->datetime      = date('Y-m-d H:i:s', strtotime($request->datetime));
            $new->content       = $request->content_text;
            $new->autor         = $request->autor;
            $new->save();

            $new->categories()->sync($request->categories);

            $filename = \Str::uuid().'_'.$new->id.'.'.$request->image->getClientOriginalExtension();
            $request->image->storeAs('public/news',$filename);

            $new->image_path    = 'storage/news/';
            $new->image_name    = $filename;
            $new->save();

            \DB::commit();

            return redirect()->route('admin.news.index')->with('notification', json_encode(['type' => 'success', 'message' => 'Datos guardados']));
        }catch (\Exception $e){
            dd($e->getMessage());

            \DB::rollBack();
            return redirect()->back()->withInput()->with('notification', json_encode(['type' => 'error', 'message' => 'Ocurrió un error']));
        }
    }

    public function edit($id)
    {
        $new = News::find($id);
        $categories = Category::pluck('name', 'id');

        return view('administration.news.form', compact('new', 'categories'));
    }

    public function update(Request $request, $id)
    {
        //dd($request->all());
        try {
            \DB::beginTransaction();

            $new = News::find($id);
            $new->title         = $request->title;
            $new->content       = $request->content_text;
            $new->datetime      = date('Y-m-d H:i:s', strtotime($request->datetime));
            $new->autor         = $request->autor;

            if ($request->image) {

                \Storage::delete('public/news/'.$new->image_name);
                $filename = \Str::uuid().'_'.$new->id.'.'.$request->image->getClientOriginalExtension();
                $request->image->storeAs('public/news',$filename);

                $new->image_path    = 'storage/news/';
                $new->image_name    = $filename;
            }

            $new->save();

            $new->categories()->sync($request->categories);

            \DB::commit();

            return redirect()->route('admin.news.index')->with('notification', json_encode(['type' => 'success', 'message' => 'Datos guardados']));
        }catch (\Exception $e){
            dd($e->getMessage());
            \DB::rollBack();
            return redirect()->back()->withInput()->with('notification', json_encode(['type' => 'error', 'message' => 'Ocurrió un error']));;
        }
    }

    public function destroy($id)
    {
        try {
            \DB::beginTransaction();

            $new = News::find($id);
            \Storage::delete('public/news/'.$new->image_name);
            $new->delete();

            \DB::commit();

            return redirect()->route('admin.news.index')->with('notification', json_encode(['type' => 'success', 'message' => 'Noticia eliminada']));
        }catch (\Exception $e){

            \DB::rollBack();
            return redirect()->back()->withInput()->with('notification', json_encode(['type' => 'error', 'message' => 'Ocurrió un error']));;
        }
    }
}

resources/views/administration/news/form.blade.php
@extends('administration.layout.app')
@section('styles')
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Noticias
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Admin</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Noticias</li>
                </ol>
            </nav>
        </div>
        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        @isset ($new)
                            <h4 class="card-title">Editar noticia noticia</h4>
                        @else
                            <h4 class="card-title">Crear noticia</h4>
                        @endisset
                        <p class="card-description">
                            Carga la información de las últimas noticias
                        </p>
                        @isset ($new)
                            {!! Form::model($new, ['route' => ['admin.news.update', $new->id], 'method' => 'PATCH','files' => true]) !!}
                        @else
                            {!! Form::open(['route' => 'admin.news.store', 'method' => 'post' ,'files' => true]) !!}
                        @endisset

                        <div class="form-group row">
                            <div class="col-sm-6">
                                <label>Título:</label>
                                {!! Form::text('title', old('title'), ['class' => 'form-control', 'required']) !!}
                                {{--<input name="title" class="form-control"/>--}}
                            </div>
                            <div class="col-sm-6">
                                <label>Autor:</label>
                                {!! Form::text('autor', old('autor'), ['class' => 'form-control']) !!}
                                {{--<input name="title" class="form-control"/>--}}
                            </div>

                        </div>

                    <div class="form-group row">
                        <div class="col-sm-3">
                            <label>Fecha:</label>
                            {!! Form::text('datetime', old('datetime') ?: (isset($new) ? date('d-m-Y H:i', strtotime($new->datetime)) : date('d-m-Y H:i')) , ['class' => 'form-control', 'data-inputmask' => "'alias': 'datetime'", 'required']) !!}
                            {{--<input name="datetime" value="{{ date('d-m-Y H:s') }}" class="form-control" data-inputmask="'alias': 'datetime'" />--}}
                        </div>
                        <div class="col-sm-3">
                            <label>Imagen:</label>
                            <input name="image" class="form-control" type="file"
                                   {{--@if (!isset($new)) required @endif--}} />
                        </div>
                        @isset ($new)
                        <div class="col-sm-3">
                            <label>Vista previa:</label>
                            <a target="_blank" href="{{ asset($new->image_path.$new->image_name) }}"><img src="{{ asset($new->image_path.$new->image_name) }}" width="30%" alt=""></a>
                        </div>
                        @endisset
                        <div class="col-sm-3">
                            <label for="categories">Categorias:</label>
                            {!! Form::select('categories[]', $categories , isset($new) ? $new->categories->pluck('id') : null , ['class' => 'form-control', 'id' => 'categories','multiple', 'required']) !!}
                        </div>
                    </div>
                        <div class="form-group">
                            <label for="exampleTextarea1">Contenido</label>
                            {!! Form::textarea('content_text', old('content_text') ?? isset($new) ? $new->content : '', ['class' => 'form-control', 'id' => 'tinyEditor']) !!}
                            {{--<textarea name="content_text" id="summernote"></textarea>--}}

                            @error('content_text')
                            <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Guardar</button>
                        <a href="{{ route('admin.news.index') }}" class="btn btn-light">Cancelar</a>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')

    <script src="https://cdn.tiny.cloud/1/le0xnl72caevg2xl8a4noobxfd3cuv10352omp6pa0ieawfi/tinymce/5/tinymce.min.js"
            referrerpolicy="origin"></script>

    <script>
        $(document).ready(function () {
            $('#categories').select2()
        })


        tinymce.init({
            menubar: false,
            height: 500,
            selector: 'textarea',
            plugins: [
                'advlist autolink lists link image charmap print preview anchor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table paste code help wordcount'
            ],
            toolbar: 'undo redo | bold italic underline strikethrough ' +
                '| fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | ' +
                'outdent indent |  numlist bullist | forecolor backcolor removeformat | emoticons | fullscreen  preview',
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script>
        $(document).ready(function () {

            $('input[name=datetime]').inputmask("datetime", {
                mask: "1-2-y h:s",
                placeholder: "dd-mm-yyyy hh:mm",
                //leapday: "-02-29",
                separator: "-",
                alias: "dd-mm-yyyy"
            });

            /*$('#summernote').summernote({
                placeholder: 'Escribe aquí tu noticia',
                tabsize: 2,
                height: 400,
                lang: "es-ES",
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'underline', 'clear']],
                    ['fontname', ['fontname']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['table', ['table']],
                    ['insert', ['link']],
                ],
            });*/
        });
    </script>

@endsection

resources/views/administration/news/index.blade.php
@extends('administration.layout.app')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Tablero
            </h3>
        </div>

        <div class="row">
            <div class="col-md-8 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">
                            <i class="fas fa-newspaper"></i>
                            Noticias
                            <a href="{{ route('admin.news.create') }}" class="fa-pull-right btn btn-info btn-xs"><i class="fas fa-plus"></i></a>
                        </h4>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Título</th>
                                    <th>Autor</th>
                                    <th>Fecha Noticia</th>
                                    <th>Categorias</th>
                                    <th>Estado</th>
                                    <th>Creado el</th>
                                    <th>Acciones</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($news as $new)
                                    <tr>
                                        <td class="font-weight-bold">
                                            {{ $new->id }}
                                        </td>
                                        <td class="text-muted">
                                            {{ $new->title }}
                                        </td>
                                        <td class="text-muted">
                                            {{ $new->autor }}
                                        </td>
                                        <td>
                                            {{ $new->datetime }}
                                        </td>
                                        <td>
                                            @foreach ($new->categories as $category)
                                                <h5><span class="badge badge-pill badge-primary ">{{ $category->name }}</span></h5>
                                            @endforeach
                                        </td>
                                        <td>
                                            <label class="badge badge-{{ $new->published ? 'success' : 'default' }} badge-pill badge-">{{ $new->published ? 'Publicado' : 'Archivado' }}</label>
                                        </td>
                                        <td>
                                            {{ $new->created_at }}
                                        </td>
                                        <td>
                                            {!! Form::open(['route' => ['admin.news.destroy', $new->id], 'method' => 'DELETE']) !!}
                                                <button type="submit" class="btn btn-outline-danger btn-xs"><i class="fas fa-trash"></i></button>
                                            {!! Form::close() !!}
                                            <a href="{{ route('admin.news.edit', $new->id) }}" class="btn btn-outline-info btn-xs"><i class="fas fa-pencil-alt"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            {{ $news->links() }}
                        </div>
                    </div>
                </div>
            </div>
    </div>
@endsection
@section('scripts')
<!-- Custom js for this page-->
<script src="/administration/js/dashboard.js"></script>
<!-- End custom js for this page-->
@endsection