routes/web.php
<?php

use App\Covenants;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::domain('ventajasmedicina.umax.edu.py')->group(function () {
      Route::get('/', function () {
          return view('landing.index');
      })->name('ventajas.medicina.index');

      Route::get('/index/portugues', function () {
          return view('landing.index_portugues');
      })->name('ventajas.medicina.portugues');
});

Route::group(['prefix'=>'admin','as'=>'admin.'], function(){
    Route::get('/', function () {
        return view('administration.index');
    })->name('dashboard')->middleware('auth');

    Route::resource('news', 'Admin\NewsController')->middleware('auth');
    Route::resource('banners', 'Admin\BannersController')->middleware('auth');
    Route::resource('covenants', 'Admin\CovenantsController')->middleware('auth');
});

Route::get('/', 'HomeController@index')->name('index');

Route::get('/noticias', 'HomeController@news')->name('noticias');

Route::get('/noticias/{id}/detail', 'HomeController@new')->name('noticias.detail');

Route::get('/divulgacion-cientifica', function (){
    $ids = [6,11,26,16,18,20,21,22,23,24,25,27,30,32,34,36,37,39,40,38,41,44,43,45];
    $news = \App\News::whereHas('categories', function ($q) {
        $q->where('id', 2);
    })->orderBy('datetime', 'desc')
        ->get();

    $news = $news->sortBy(function($model) use ($ids) {
        return array_search($model->getKey(), $ids);
    });

    return view('news.divulgacion', compact('news'));

})->name('divulgacion');


Route::get('/nosotros', function () {
    return view('about.index');
})->name('about');

Route::get('/medicina', function () {
    return view('about.medicina');
})->name('medicina');

Route::get('/enfermeria', function () {
    return view('about.enfermeria');
})->name('enfermeria');

Route::get('/virtual', function () {
    return view('about.virtual');
})->name('virtual');

/*
 * Convenios
 */
Route::get('/convenios', function () {
    $covenants = Covenants::orderBy('created_at', 'desc')->get();
    return view('about.convenios', compact('covenants'));
})->name('convenios');

Route::get('/convenios/{id}', function ($id) {
    $covenant = Covenants::find($id);
    return view('about.convenio_interna', compact('covenant'));
})->name('convenio.interna');

Route::get('/convenios_bk', function () {
    return view('about.convenios_bk');
});

Route::get('/convenios_bk/1', function () {
    return view('about.detail-convenio');
})->name('convenio-1');

Route::get('/convenios_bk/2', function () {
    return view('about.detail-convenio2');
})->name('convenio-2');

Route::get('/convenios_bk/3', function () {
    return view('about.detail-convenio3');
})->name('convenio-3');

Route::get('/convenios_bk/4', function () {
    return view('about.detail-convenio4');
})->name('convenio-4');

Route::get('/convenios_bk/5', function () {
    return view('about.detail-convenio5');
})->name('convenio-5');

Route::get('/convenios_bk/6', function () {
    return view('about.detail-convenio6');
})->name('convenio-6');



/*
 * Carreras
 */
Route::get('/postgrado', function () {
    return view('carreras.postgrado');
})->name('postgrado');

Route::get('/pregrado/tecnico-superior-farmacia', function () {
    return view('carreras.pregrado.tecnico_superior_farmacia');
})->name('pregrado-1');

Route::get('/pregrado/tecnico-superior-radiologia', function () {
    return view('carreras.pregrado.tecnico_superior_radiologia');
})->name('pregrado-2');

Route::get('/pregrado/tecnico-superior-laboratorio-clinico', function () {
    return view('carreras.pregrado.tecnico_superior_laboratorio');
})->name('pregrado-3');

Route::get('/pregrado/tecnico-superior-masaje-terapeutico', function () {
    return view('carreras.pregrado.tecnico_superior_masaje');
})->name('pregrado-4');

Route::get('/pregrado/tecnico-superior-enfermeria', function () {
    return view('carreras.pregrado.tecnico_superior_enfermeria');
})->name('pregrado-5');



Route::get('/contacto', function () {
    return view('about.contacto');
})->name('contacto');


Route::get('/maestria', function () {
    return view('postgrado.maestria');
})->name('maestria');

Route::get('/especializacion', function () {
    return view('postgrado.especializacion');
})->name('especializacion');

Route::get('/diplomado', function () {
    return view('postgrado.diplomado');
})->name('diplomado');

Route::get('/extension', function () {
    return view('extension.index');
})->name('extension');

Route::get('/investigacion', function () {
    return view('extension.investigacion');
})->name('investigacion');

Route::get('/politicas-investigacion', function () {
    return view('extension.politicas-investigacion');
})->name('politicas-investigacion');

Route::get('/lineas-investigacion', function () {
    return view('extension.lineas-investigacion');
})->name('lineas-investigacion');

Route::get('/actividades-investigacion', function () {
    return view('extension.actividades-investigacion');
})->name('actividades-investigacion');

Route::get('/investigadores-asociados', function () {
    return view('extension.investigadores-asociados');
})->name('investigadores-asociados');

Route::get('/revista-cientifica', function () {
    return view('extension.revista-cientifica');
})->name('revista-cientifica');

Route::get('/declaracion-privacidad', function () {
    return view('extension.declaracion-privacidad');
})->name('declaracion-privacidad');

Route::get('/equipo-editorial', function () {
    return view('extension.equipo-editorial');
})->name('equipo-editorial');

Route::get('/archivos', function () {
    return view('extension.archivos');
})->name('archivos');

Route::get('/envios', function () {
    return view('extension.envios');
})->name('envios');

Route::get('/revista-cientifica', function () {
    return view('extension.revista-cientifica');
})->name('revista-cientifica');

Route::get('/pastoral', function () {
    return view('extension.pastoral');
})->name('pastoral');

Route::get('/bienestar-estudiantil', function () {
    return view('bienestar.bienestar');
})->name('bienestar');

Route::get('/egresados', function () {
    return view('about.egresados');
})->name('egresados');

Route::get('/noticias/2', function () {
    return view('news.news-detail-2');
})->name('news-detail-2');

Route::get('/noticias/3', function () {
    return view('news.news-detail-3');
})->name('news-detail-3');

Route::get('/noticias/4', function () {
    return view('news.news-detail-4');
})->name('news-detail-4');

Route::get('/noticias/5', function () {
    return view('news.news-detail-5');
})->name('news-detail-5');

Route::get('/biblioteca-virtual', function () {
    return view('about.biblioteca');
})->name('biblioteca');

/*
 * Investigación -> Núcleos de Investigación
 */
Route::get('/innovacion-medica', function () {
    return view('nucleos.innovacion-medica');
})->name('innovacion-medica');

Route::get('/enfermedades-infecciosas', function () {
    return view('nucleos.enfermedades-infecciosas');
})->name('enfermedades-infecciosas');

Route::get('/nutricion-geriatria', function () {
    return view('nucleos.nutricion-geriatria');
})->name('nutricion-geriatria');

Route::get('/bioestadistica-aplicada-salud', function () {
    return view('nucleos.bioestadistica-aplicada-salud');
})->name('bioestadistica-aplicada-salud');

Route::get('/donacion-transplante-organos', function () {
    return view('nucleos.donacion-transplante-organos');
})->name('donacion-transplante-organos');

Route::get('/psiquiatria-salud-mental', function () {
    return view('nucleos.salud-mental');
})->name('salud-mental');

Route::get('/tecnologia-informacion-comunicacion-salud', function () {
    return view('nucleos.tecnologia-informacion-comunicacion-salud');
})->name('tecnologia-informacion-comunicacion-salud');


/*
 * MAILING
 */
Route::get('/mail/send/future', 'EmailsController@future')->name('mail.send.future');
Route::get('/mail/send/contact', 'EmailsController@contact')->name('mail.send.contact');

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
//http://ventajasmedicina.umax.edu.py/

/*Route::domain('{account}.example.com')->group(function () {
    Route::get('user/{id}', function ($account, $id) {
        //
    });
});*/

Route::get('ventajas/es', function (){
    return view('landing.index');
});
Route::get('ventajas/pt', function (){
    return view('landing.index_portugues');
});

app/Covenants.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Covenants extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'content',
        'image_path',
        'internal_image_path',
        'external_link',
    ];
}

app/Http/Controllers/Admin/CovenantsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Covenants;
use App\Http\Controllers\Controller;
use App\Mail\contactMail;
use App\Mail\futureMail;
use App\News;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;

class CovenantsController extends Controller
{
    public function index(Request $request)
    {
        $covenants = Covenants::orderBy('created_at', 'DESC')->paginate(20);

        return view('administration.covenants.index', compact('covenants'));
    }

    public function create()
    {
        return view('administration.covenants.form');
    }

    public function store(Request $request)
    {
        try {
            \DB::beginTransaction();

            $covenants = new Covenants();
            $covenants->title         = $request->title;
            $covenants->content       = $request->content_text;
            $covenants->external_link = $request->external_link;
            $covenants->save();

            if ($request->image_path) {
                $filename = \Str::uuid().'_'.$covenants->id.'.'.$request->image_path->getClientOriginalExtension();
                $request->image_path->storeAs('public/covenants',$filename);
                $covenants->image_path    = 'covenants/'.$filename;
            }

            if ($request->internal_image_path) {
                $filename = \Str::uuid().'_internal_'.$covenants->id.'.'.$request->internal_image_path->getClientOriginalExtension();
                $request->internal_image_path->storeAs('public/covenants',$filename);
                $covenants->internal_image_path    = 'covenants/'.$filename;
            }

            $covenants->save();

            \DB::commit();

            //dd($covenants);

            return redirect()->route('admin.covenants.index')->with('notification', json_encode(['type' => 'success', 'message' => 'Datos guardados']));
        }catch (\Exception $e){
            \DB::rollBack();
            dd($e->getMessage());
            return redirect()->back()->withInput()->with('notification', json_encode(['type' => 'error', 'message' => 'Ocurrió un error']));
        }
    }

    public function edit($id)
    {
        $covenants = Covenants::find($id);
        //dd($covenants);

        return view('administration.covenants.form', compact('covenants'));
    }

    public function update(Request $request, $id)
    {
        //dd($request->all());
        try {
            \DB::beginTransaction();

            $covenants = Covenants::find($id);

            $covenants->title         = $request->title;
            $covenants->content       = $request->content_text;
            $covenants->external_link = $request->external_link;
            $covenants->save();

            if ($request->image_path) {
                Storage::delete('public/'.$covenants->image_path);

                $filename = \Str::uuid().'_'.$covenants->id.'.'.$request->image_path->getClientOriginalExtension();
                $request->image_path->storeAs('public/covenants',$filename);
                $covenants->image_path    = 'covenants/'.$filename;
            }

            if ($request->internal_image_path) {
                Storage::delete('public/'.$covenants->internal_image_path);

                $filename = \Str::uuid().'_internal_'.$covenants->id.'.'.$request->internal_image_path->getClientOriginalExtension();
                $request->internal_image_path->storeAs('public/covenants',$filename);
                $covenants->internal_image_path    = 'covenants/'.$filename;
            }

            $covenants->save();

            \DB::commit();

            return redirect()->route('admin.covenants.index')->with('notification', json_encode(['type' => 'success', 'message' => 'Datos guardados']));
        }catch (\Exception $e){
            \DB::rollBack();
            dd($e->getMessage());
            return redirect()->back()->withInput()->with('notification', json_encode(['type' => 'error', 'message' => 'Ocurrió un error']));;
        }
    }

    public function destroy($id)
    {
        try {
            \DB::beginTransaction();

            $covenant = Covenants::find($id);
            \Storage::delete('public/'.$covenant->image_path);
            \Storage::delete('public/'.$covenant  ->internal_image_path);
            $covenant->delete();

            \DB::commit();

            return redirect()->route('admin.covenants.index')->with('notification', json_encode(['type' => 'success', 'message' => 'Convenio eliminado']));
        }catch (\Exception $e){

            \DB::rollBack();

            dd($e->getMessage());
            return redirect()->back()->withInput()->with('notification', json_encode(['type' => 'error', 'message' => 'Ocurrió un error']));;
        }
    }
}

resources/views/administration/covenants/form.blade.php
@extends('administration.layout.app')
@section('styles')
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Convenios
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Admin</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Convenios</li>
                </ol>
            </nav>
        </div>
        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        @isset ($covenants)
                            <h4 class="card-title">Editar convenio</h4>
                        @else
                            <h4 class="card-title">Crear convenio</h4>
                        @endisset
                        <p class="card-description">
                            Carga la información del convenio
                        </p>
                        @isset ($covenants)
                            {!! Form::model($covenants, ['route' => ['admin.covenants.update', $covenants->id], 'method' => 'PATCH','files' => true]) !!}
                        @else
                            {!! Form::open(['route' => 'admin.covenants.store', 'method' => 'post' ,'files' => true]) !!}
                        @endisset

                        <div class="form-group row">
                            <div class="col-sm-6">
                                <label>Título:</label>
                                {!! Form::text('title', old('title'), ['class' => 'form-control', 'required']) !!}
                            </div>

                            <div class="col-sm-3">
                                <label>Imagen convenio:</label>
                                <input name="image_path" class="form-control" type="file"/>
                            </div>

                            <div class="col-sm-3">
                                <label>Imagen Interna:</label>
                                <input name="internal_image_path" class="form-control" type="file"/>
                            </div>

                            <div class="col-sm-6">
                                <label>URL Externo:</label>
                                {!! Form::text('external_link', old('external_link'), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group">

                            <label for="exampleTextarea1">Textarea</label>
                            {!! Form::textarea('content_text', old('content_text') ?? isset($covenants) ? $covenants->content : '', ['class' => 'form-control', 'id' => 'tinyEditor']) !!}
                            {{--<textarea name="content_text" id="summernote"></textarea>--}}
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Guardar</button>
                        <a href="{{ route('admin.covenants.index') }}" class="btn btn-light">Cancelar</a>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')

    <script src="https://cdn.tiny.cloud/1/le0xnl72caevg2xl8a4noobxfd3cuv10352omp6pa0ieawfi/tinymce/5/tinymce.min.js"
            referrerpolicy="origin"></script>

    <script>
        $(document).ready(function () {
            $('#categories').select2()
        })


        tinymce.init({
            menubar: false,
            height: 500,
            selector: 'textarea',
            plugins: [
                'advlist autolink lists link image charmap print preview anchor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table paste code help wordcount'
            ],
            toolbar: 'undo redo | bold italic underline strikethrough ' +
                '| fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | ' +
                'outdent indent |  numlist bullist | forecolor backcolor removeformat | emoticons | fullscreen  preview',
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script>
        $(document).ready(function () {

            $('input[name=datetime]').inputmask("datetime", {
                mask: "1-2-y h:s",
                placeholder: "dd-mm-yyyy hh:mm",
                //leapday: "-02-29",
                separator: "-",
                alias: "dd-mm-yyyy"
            });

            /*$('#summernote').summernote({
                placeholder: 'Escribe aquí tu noticia',
                tabsize: 2,
                height: 400,
                lang: "es-ES",
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'underline', 'clear']],
                    ['fontname', ['fontname']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['table', ['table']],
                    ['insert', ['link']],
                ],
            });*/
        });
    </script>

@endsection

resources/views/administration/covenants/index.blade.php
@extends('administration.layout.app')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Tablero
            </h3>
        </div>

        <div class="row">
            <div class="col-md-8 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">
                            <i class="fas fa-newspaper"></i>
                            Convenios
                            <a href="{{ route('admin.covenants.create') }}" class="fa-pull-right btn btn-info btn-xs"><i class="fas fa-plus"></i></a>
                        </h4>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Título</th>
                                    <th>Imagen</th>
                                    <th>Imagen Interna</th>
                                    <th>Link Externo</th>
                                    <th>Creado el</th>
                                    <th>Acciones</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($covenants as $covenant)
                                    <tr>
                                        <td class="font-weight-bold">
                                            {{ $covenant->id }}
                                        </td>
                                        <td class="text-muted">
                                            {{ $covenant->title }}
                                        </td>
                                        <td class="text-muted">
                                            @if ($covenant->image_path)
                                                <a href="{{ asset('storage/'.$covenant->image_path) }}" target="_blank"><img height="50px" src="{{ asset('storage/'.$covenant->image_path) }}" alt=""></a>
                                            @endif
                                        </td>
                                        <td>
                                            @if ($covenant->internal_image_path)
                                                <a href="{{ asset('storage/'.$covenant->internal_image_path) }}" target="_blank"><img height="50px" src="{{ asset('storage/'.$covenant->internal_image_path) }}" alt=""></a>
                                            @endif
                                        </td>
                                        <td>
                                            {{ $covenant->created_at }}
                                        </td>
                                        <td>
                                            {!! Form::open(['route' => ['admin.covenants.destroy', $covenant->id], 'method' => 'DELETE']) !!}
                                                <button type="submit" class="btn btn-outline-danger btn-xs"><i class="fas fa-trash"></i></button>
                                            {!! Form::close() !!}
                                            <a href="{{ route('admin.covenants.edit', $covenant->id) }}" class="btn btn-outline-info btn-xs"><i class="fas fa-pencil-alt"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            {{ $covenants->links() }}
                        </div>
                    </div>
                </div>
            </div>
    </div>
@endsection
@section('scripts')
<!-- Custom js for this page-->
<script src="/administration/js/dashboard.js"></script>
<!-- End custom js for this page-->
@endsection